"""
COMPREHENSIVE_CLASS_COLORS.py - Complete color palette for all classification levels

This file maps all superclasses, pathways, classes, and subclasses from 
feature_metadata_enriched.csv to distinct hex colors.

Generated from the enriched metadata with automated color assignment.
Use these definitions to replace or extend CLASS_COLORS in config.py
"""

COMPREHENSIVE_CLASS_COLORS = {
    # ---- ClassyFire superclass (14) -----------------------------------
    "Acetylides":                            "#d83636",
    "Alkaloids and derivatives":                            "#d87b36",
    "Benzenoids":                            "#d8c136",
    "Hydrocarbon derivatives":                            "#aad836",
    "Hydrocarbons":                            "#64d836",
    "Lipids and lipid-like molecules":                            "#36d84d",
    "Organic acids and derivatives":                            "#36d893",
    "Organic nitrogen compounds":                            "#36d8d8",
    "Organic oxygen compounds":                            "#3693d8",
    "Organohalogen compounds":                            "#364dd8",
    "Organoheterocyclic compounds":                            "#6436d8",
    "Organometallic compounds":                            "#aa36d8",
    "Organosulfur compounds":                            "#d836c1",
    "Phenylpropanoids and polyketides":                            "#d8367b",

    # ---- NPClassifier pathway (6) ------------------------------------
    "Alkaloids":                            "#e54444",
    "Amino acids and Peptides":                            "#e5e544",
    "Fatty acids":                            "#44e544",
    "Polyketides":                            "#44e5e5",
    "Shikimates and Phenylpropanoids":                            "#4444e5",
    "Terpenoids":                            "#e544e5",

    # ---- NPClassifier class (80) -------------------------------------------
    "2-pyrone derivatives":                            "#e04e4e",
    "Abietane diterpenoids":                            "#e0594e",
    "Acyclic monoterpenoids":                            "#e0644e",
    "Amarylidaceae alkaloids":                            "#e06f4e",
    "Aminoacids":                            "#e07a4e",
    "Anthranillic acid derivatives":                            "#e0854e",
    "Anthraquinones and anthrones":                            "#e0904e",
    "Apocarotenoids (β-)":                            "#e09b4e",
    "Aristolane sesquiterpenoids":                            "#e0a64e",
    "Aromadendrane sesquiterpenoids":                            "#e0b04e",
    "Aspidosperma type":                            "#e0bb4e",
    "Bergamotane sesquiterpenoids":                            "#e0c64e",
    "Bisabolane sesquiterpenoids":                            "#e0d14e",
    "Botryane sesquiterpenoids":                            "#e0dc4e",
    "Branched fatty acids":                            "#d9e04e",
    "Cadinane sesquiterpenoids":                            "#cee04e",
    "Camphane monoterpenoids":                            "#c3e04e",
    "Carane monoterpenoids":                            "#b8e04e",
    "Carbocyclic fatty acids":                            "#ade04e",
    "Carboline alkaloids":                            "#a2e04e",
    "Caryophyllane sesquiterpenoids":                            "#97e04e",
    "Catechols with side chains":                            "#8ce04e",
    "Cembrane diterpenoids":                            "#81e04e",
    "Chalcones":                            "#76e04e",
    "Cinnamic acids and derivatives":                            "#6be04e",
    "Copaane sesquiterpenoids":                            "#60e04e",
    "Copacamphane sesquiterpenoids":                            "#55e04e",
    "Corynanthe type":                            "#4ee052",
    "Cubebane sesquiterpenoids":                            "#4ee05d",
    "Cycloeudesmane sesquiterpenoids":                            "#4ee068",
    "Depsides":                            "#4ee073",
    "Dipeptides":                            "#4ee07d",
    "Drimane sesquiterpenoids":                            "#4ee088",
    "Elemane sesquiterpenoids":                            "#4ee093",
    "Eudesmane sesquiterpenoids":                            "#4ee09e",
    "Fatty alcohols":                            "#4ee0a9",
    "Fatty aldehydes":                            "#4ee0b4",
    "Flavanones":                            "#4ee0bf",
    "Furans":                            "#4ee0ca",
    "Germacrane sesquiterpenoids":                            "#4ee0d5",
    "Guaiane sesquiterpenoids":                            "#4ee0e0",
    "Halogenated hydrocarbons":                            "#4ed5e0",
    "Hasubanan alkaloids":                            "#4ecae0",
    "Hydrocarbons":                            "#4ebfe0",
    "Iridoids monoterpenoids":                            "#4eb4e0",
    "Jasmonic acids":                            "#4ea9e0",
    "Labdane diterpenoids":                            "#4e9ee0",
    "Lactones":                            "#4e93e0",
    "Megastigmanes":                            "#4e88e0",
    "Menthane monoterpenoids":                            "#4e7de0",
    "Minor lignans":                            "#4e73e0",
    "Miscellaneous meroterpenoids":                            "#4e68e0",
    "Monocyclic monoterpenoids":                            "#4e5de0",
    "N-acyl amines":                            "#4e52e0",
    "Oplopane sesquiterpenoids":                            "#554ee0",
    "Oxo fatty acids":                            "#604ee0",
    "Oxygenated hydrocarbons":                            "#6b4ee0",
    "Phenanthrenes":                            "#764ee0",
    "Phenazine alkaloids":                            "#814ee0",
    "Phenylalanine-derived alkaloids":                            "#8c4ee0",
    "Phenylethylamines":                            "#974ee0",
    "Pinane monoterpenoids":                            "#a24ee0",
    "Piperidine alkaloids":                            "#ad4ee0",
    "Polyamines":                            "#b84ee0",
    "Presilphiperfolane and Probotryane sesquiterpenoids":                            "#c34ee0",
    "Purine alkaloids":                            "#ce4ee0",
    "Pyrazine and Piperazine alkaloids":                            "#d94ee0",
    "Pyridine alkaloids":                            "#e04edc",
    "Quinazoline alkaloids":                            "#e04ed1",
    "Shikimic acids and derivatives":                            "#e04ec6",
    "Simple amide alkaloids":                            "#e04ebb",
    "Simple diketopiperazine alkaloids":                            "#e04eb0",
    "Simple indole alkaloids":                            "#e04ea6",
    "Simple phenolic acids":                            "#e04e9b",
    "Thujane monoterpenoids":                            "#e04e90",
    "Thujopsane sesquiterpenoids":                            "#e04e85",
    "Unsaturated fatty acids":                            "#e04e7a",
    "Wax diesters":                            "#e04e6f",
    "Wax monoesters":                            "#e04e64",
    "p-Terphenyls":                            "#e04e59",

    # ---- ClassyFire subclass (103) --------------------------------------
    "1,3-dioxanes":                            "#ea5d5d",
    "1-benzopyrans":                            "#ea665d",
    "1-hydroxy-2-unsubstituted benzenoids":                            "#ea6e5d",
    "1-hydroxy-4-unsubstituted benzenoids":                            "#ea765d",
    "2-benzopyrans":                            "#ea7e5d",
    "Acetylenes":                            "#ea865d",
    "Acrylic acids and derivatives":                            "#ea8f5d",
    "Alcohols and polyols":                            "#ea975d",
    "Alkanes":                            "#ea9f5d",
    "Alkyl chlorides":                            "#eaa75d",
    "Alkyl fluorides":                            "#eaaf5d",
    "Alpha-halocarboxylic acids and derivatives":                            "#eab85d",
    "Amines":                            "#eac05d",
    "Amino acids, peptides, and analogues":                            "#eac85d",
    "Aminophenyl ethers":                            "#ead05d",
    "Aminoquinolines and derivatives":                            "#ead85d",
    "Anilides":                            "#eae15d",
    "Aniline and substituted anilines":                            "#eae95d",
    "Anisoles":                            "#e3ea5d",
    "Aryl chlorides":                            "#dbea5d",
    "Benzenesulfonamides":                            "#d3ea5d",
    "Benzodiazines":                            "#cbea5d",
    "Benzoic acids and derivatives":                            "#c2ea5d",
    "Benzonitriles":                            "#baea5d",
    "Benzoyl derivatives":                            "#b2ea5d",
    "Benzyloxycarbonyls":                            "#aaea5d",
    "Beta hydroxy acids and derivatives":                            "#a2ea5d",
    "Biphenyls and derivatives":                            "#99ea5d",
    "Branched unsaturated hydrocarbons":                            "#91ea5d",
    "Butyrophenones":                            "#89ea5d",
    "Carbazoles":                            "#81ea5d",
    "Carbonic acid diesters":                            "#79ea5d",
    "Carbonyl compounds":                            "#70ea5d",
    "Carboxylic acid derivatives":                            "#68ea5d",
    "Carboxylic acids":                            "#60ea5d",
    "Cinnamic acids":                            "#5dea63",
    "Cumenes":                            "#5dea6b",
    "Cycloalkanes":                            "#5dea73",
    "Cytisine and derivatives":                            "#5dea7b",
    "Delta valerolactones":                            "#5dea84",
    "Dialkyldisulfides":                            "#5dea8c",
    "Dicarboxylic acids and derivatives":                            "#5dea94",
    "Diphenylethers":                            "#5dea9c",
    "Diphenylmethanes":                            "#5deaa4",
    "Diterpenoids":                            "#5deaad",
    "Dithioacetals":                            "#5deab5",
    "Enynes":                            "#5deabd",
    "Ethers":                            "#5deac5",
    "Fatty acid esters":                            "#5deacd",
    "Fatty acids and conjugates":                            "#5dead6",
    "Fatty alcohol esters":                            "#5deade",
    "Fatty alcohols":                            "#5deae6",
    "Fatty aldehydes":                            "#5de6ea",
    "Gamma butyrolactones":                            "#5ddeea",
    "Gamma-keto acids and derivatives":                            "#5dd6ea",
    "Halobenzenes":                            "#5dcdea",
    "Halomethanes":                            "#5dc5ea",
    "Hexacarboxylic acids and derivatives":                            "#5dbdea",
    "Homolycorine-type amaryllidaceae alkaloids":                            "#5db5ea",
    "Imidazoles":                            "#5dadea",
    "Imidazolidines":                            "#5da4ea",
    "Indanones":                            "#5d9cea",
    "Indolecarboxylic acids and derivatives":                            "#5d94ea",
    "Indoles":                            "#5d8cea",
    "Lineolic acids and derivatives":                            "#5d84ea",
    "Methoxybenzenes":                            "#5d7bea",
    "Methylpyridines":                            "#5d73ea",
    "Monoterpenoids":                            "#5d6bea",
    "N-alkylpyrrolidines":                            "#5d63ea",
    "N-phenylureas":                            "#605dea",
    "Naphthalene sulfonic acids and derivatives":                            "#685dea",
    "Nitrobenzenes":                            "#705dea",
    "O-methylated flavonoids":                            "#795dea",
    "Olefins":                            "#815dea",
    "Organosilicon compounds":                            "#895dea",
    "Ortho esters":                            "#915dea",
    "Oxazolidines":                            "#995dea",
    "Peroxycarboxylic acids and derivatives":                            "#a25dea",
    "Phenethylamines":                            "#aa5dea",
    "Phenoxy compounds":                            "#b25dea",
    "Phenylacetamides":                            "#ba5dea",
    "Phenylbenzodioxanes":                            "#c25dea",
    "Phenylpropanes":                            "#cb5dea",
    "Phenylpropenes":                            "#d35dea",
    "Phenylpyridines":                            "#db5dea",
    "Phenylpyrrolidines":                            "#e35dea",
    "Phosphate esters":                            "#ea5de9",
    "Piperazines":                            "#ea5de1",
    "Pyranones and derivatives":                            "#ea5dd8",
    "Pyrazines":                            "#ea5dd0",
    "Pyrazoles":                            "#ea5dc8",
    "Pyridoindoles":                            "#ea5dc0",
    "Pyrimidines and pyrimidine derivatives":                            "#ea5db8",
    "Pyrrolidinylpyridines":                            "#ea5daf",
    "Sesquiterpenoids":                            "#ea5da7",
    "Styrenes":                            "#ea5d9f",
    "Tetracarboxylic acids and derivatives":                            "#ea5d97",
    "Toluenes":                            "#ea5d8f",
    "Triazoles":                            "#ea5d86",
    "Tricarboxylic acids and derivatives":                            "#ea5d7e",
    "Triterpenoids":                            "#ea5d76",
    "Unsaturated aliphatic hydrocarbons":                            "#ea5d6e",
    "Vinyl fluorides":                            "#ea5d66",

    # ---- Special / fallback (always gray) -----------------------------------
    "Unknown":                               "#cccccc",
    "Unclassified":                          "#aaaaaa",
    "Other":                                 "#bbbbbb",
}
